# Generated by Django 5.0.6 on 2024-09-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="id",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
