# Generated by Django 5.0.6 on 2024-09-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0002_alter_people_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="role",
            field=models.CharField(default="tag", max_length=20),
        ),
        migrations.RemoveField(
            model_name="people",
            name="code",
        ),
        migrations.RemoveField(
            model_name="people",
            name="intro",
        ),
        migrations.RemoveField(
            model_name="people",
            name="urls",
        ),
        migrations.AlterField(
            model_name="people",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.DeleteModel(
            name="PeopleType",
        ),
    ]
