from __future__ import annotations

"""
Read the CSV generated by scan_videos_to_csv.py and write back video info into
MongoDB jdb.movies documents (by href). Also mark the CSV row as written.

Video metadata:
- Always store: root, path (relative), abs_path, size_bytes
- Optionally probe via ffprobe to get: duration_seconds, width, height, bitrate,
  video_codec, audio_codec

CSV expectations:
- Columns: root, relpath, code, href, written (written may be missing; will be added)
- Only rows with non-empty href are processed.
- With --incremental (default), skip rows whose 'written' is truthy.
"""

import argparse
import os
import json
import subprocess
from pathlib import Path
from typing import Any, Dict, List

from pymongo import MongoClient
from tqdm import tqdm

try:
    import pandas as pd  # type: ignore
except Exception:
    pd = None  # type: ignore


def ffprobe_metadata(path: Path, ffprobe_path: str = "ffprobe", timeout: int = 20) -> Dict[str, Any]:
    try:
        cmd = [
            ffprobe_path,
            "-v", "error",
            "-print_format", "json",
            "-show_format",
            "-show_streams",
            str(path),
        ]
        out = subprocess.check_output(cmd, timeout=timeout)
        info = json.loads(out.decode("utf-8", errors="ignore"))
        res: Dict[str, Any] = {}
        fmt = info.get("format", {})
        if fmt:
            if "duration" in fmt:
                try:
                    res["duration_seconds"] = float(fmt["duration"])  # seconds
                except Exception:
                    pass
            if "bit_rate" in fmt:
                try:
                    res["bitrate"] = int(fmt["bit_rate"])  # bps
                except Exception:
                    pass
        vcodec = None
        acodec = None
        width = height = None
        for s in info.get("streams", []) or []:
            if s.get("codec_type") == "video" and vcodec is None:
                vcodec = s.get("codec_name")
                width = s.get("width")
                height = s.get("height")
            elif s.get("codec_type") == "audio" and acodec is None:
                acodec = s.get("codec_name")
        if vcodec:
            res["video_codec"] = vcodec
        if acodec:
            res["audio_codec"] = acodec
        if width and height:
            res["width"] = int(width)
            res["height"] = int(height)
        return res
    except Exception:
        return {}


def main():
    ap = argparse.ArgumentParser(description="Write back video info to Mongo from CSV list")
    ap.add_argument("--csv", required=True, help="input CSV path (results)")
    ap.add_argument("--mongo", default=os.getenv("MONGO_URL", "mongodb://localhost:27017/"))
    ap.add_argument("--db", default=os.getenv("MONGO_DB_NAME", "jdb"))
    ap.add_argument("--ffprobe", default=os.getenv("FFPROBE", "ffprobe"))
    ap.add_argument("--no-probe", action="store_true", help="do not call ffprobe; only size")
    ap.add_argument("--incremental", action="store_true", help="skip rows already written")
    args = ap.parse_args()

    client = MongoClient(args.mongo)
    col = client[args.db]["movies"]

    # Load CSV
    headers = ["root", "relpath", "code", "href", "written"]
    rows: List[Dict[str, Any]] = []
    if pd is not None:
        df = pd.read_csv(args.csv)
        for _, r in df.iterrows():
            rows.append({
                "root": str(r.get("root", "")),
                "relpath": str(r.get("relpath", "")),
                "code": "" if (hasattr(pd, 'isna') and pd.isna(r.get("code"))) else str(r.get("code", "")),
                "href": "" if (hasattr(pd, 'isna') and pd.isna(r.get("href"))) else str(r.get("href", "")),
                "written": False if (hasattr(pd, 'isna') and pd.isna(r.get("written"))) else bool(r.get("written", False)),
            })
    else:
        import csv
        with open(args.csv, "r", newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for r in reader:
                rows.append({
                    "root": r.get("root", ""),
                    "relpath": r.get("relpath", ""),
                    "code": r.get("code", ""),
                    "href": r.get("href", ""),
                    "written": r.get("written", "") in ("1", "true", "True", "yes"),
                })

    # Process
    updated = 0
    processed = 0
    for row in tqdm(rows, desc="Update DB", unit="row"):
        href = (row.get("href") or "").strip()
        if not href:
            continue
        if args.incremental and row.get("written"):
            continue
        root = Path(row.get("root") or "")
        rel = Path(row.get("relpath") or "")
        abspath = (root / rel)

        info: Dict[str, Any] = {
            "root": str(root),
            "path": rel.as_posix(),
            "abs_path": abspath.as_posix(),
        }
        try:
            info["size_bytes"] = int(abspath.stat().st_size)
        except Exception:
            info["size_bytes"] = None

        if not args.no_probe and abspath.exists():
            meta = ffprobe_metadata(abspath, ffprobe_path=args.ffprobe)
            info.update(meta)

        # Update movie by href
        res = col.update_one({"href": href}, {"$set": {"video": info}})
        if res.matched_count:
            updated += 1
            row["written"] = True
        processed += 1

    # Save CSV back (preserve order; if pandas present, keep columns)
    if pd is not None:
        df_out = pd.DataFrame(rows, columns=headers)
        # Sort by code for consistency
        df_out.sort_values(by=["code", "root", "relpath"], inplace=True, kind="mergesort")
        df_out.to_csv(args.csv, index=False)
    else:
        import csv
        rows_sorted = sorted(rows, key=lambda r: ((r.get("code") or "").upper(), r.get("root", ""), r.get("relpath", "")))
        with open(args.csv, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=headers)
            w.writeheader()
            w.writerows(rows_sorted)

    print(f"Done. processed={processed}, updated={updated}, csv={args.csv}")


if __name__ == "__main__":
    main()

