# Generated by Django 5.0.6 on 2024-09-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="duration_min",
            new_name="duration",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="parsed",
            new_name="processed",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="published_date",
            new_name="release_date",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="actors",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="favorite",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="info",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="location",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="series",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="studio",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="tags",
        ),
        migrations.AddField(
            model_name="movie",
            name="cover",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="current_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="original_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="video_path",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="movie",
            name="video_src",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
