# Generated by Django 5.0.6 on 2024-09-05 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_rename_duration_min_movie_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="code",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="cover",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="movie",
            name="current_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name="movie",
            name="original_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="movie",
            name="video_src",
            field=models.CharField(default="", max_length=500),
        ),
    ]
