# Generated by Django 5.0.6 on 2024-09-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0003_alter_movie_code_alter_movie_cover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="rater",
            field=models.IntegerField(default=0),
        ),
    ]
