# Generated by Django 5.1 on 2024-09-05 16:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0005_rename_original_title_movie_origin_title"),
        ("person", "0004_rename_people_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="act_movies", to="person.group"),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_movies",
                to="person.group",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="local",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="maker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="make_movies",
                to="person.group",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="may_like",
            field=models.ManyToManyField(
                related_name="may_like_movies", to="movie.movie"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publish_movies",
                to="person.group",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="related",
            field=models.ManyToManyField(
                related_name="related_movies", to="movie.movie"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="series",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series_movies",
                to="person.group",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="tags",
            field=models.ManyToManyField(related_name="tag_movies", to="person.group"),
        ),
        migrations.CreateModel(
            name="Magnet",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("meta", models.CharField(default="", max_length=255)),
                ("tags", models.CharField(default="", max_length=255)),
                ("time", models.DateField(default=datetime.date.today)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magnets",
                        to="movie.movie",
                    ),
                ),
            ],
        ),
    ]
