# Generated by Django 5.1 on 2024-09-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0006_movie_actors_movie_director_movie_local_movie_maker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="current_title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="origin_title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
