# Generated by Django 5.1 on 2024-09-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0007_alter_movie_current_title_alter_movie_origin_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="in_database",
            field=models.BooleanField(default=False),
        ),
    ]
