# Generated by Django 5.1 on 2024-09-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0008_movie_in_database"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="current_title",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="movie",
            name="origin_title",
            field=models.CharField(default="", max_length=500),
        ),
    ]
