# Generated by Django 5.1 on 2024-10-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0009_alter_movie_current_title_alter_movie_origin_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="my_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="current_title",
            field=models.CharField(default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="origin_title",
            field=models.CharField(default="", max_length=500, null=True),
        ),
    ]
